In [3]:
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.
#Ans.
#Yes, there is a difference in the data type of the list_ and array_list variables. list_ is a list of strings, while array_list is a NumPy array of strings.

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


In [4]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.
#Ans.
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
for elem in list_:
    print(type(elem))

# Print data type of each element in array_list
for elem in array_list:
    print(type(elem))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [5]:
#Q3. Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? 
#If so then print the data types of each and every element present in both the variables, list_ and arra_list.
#Ans.
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
for elem in list_:
    print(type(elem))

# Print data type of each element in array_list
for elem in array_list:
    print(type(elem))

#Yes, there will be a difference in the data type of the elements present in list_ and array_list. the data type of each element in list_ is a string, while the data type of each element in array_list is an integer (int).

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [9]:
#Q4. Write a code to find the following characteristics of variable, num_array:
#(i) shape
#(ii) size
#Ans.
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

print(num_array.shape)
print(num_array.size)

(2, 3)
6


In [18]:
#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
#Ans.
import numpy as np

# Create a 3x3 matrix containing zeros only
zero_matrix = np.zeros((3, 3))

print(zero_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?
#Ans.
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
